# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/lightweight-iot-client/examples/client

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/lightweight-iot-client

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/lightweight-iot-client/CMakeFiles /home/pi/lightweight-iot-client/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/lightweight-iot-client/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named submodule_update

# Build rule for target.
submodule_update: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 submodule_update
.PHONY : submodule_update

# fast build rule for target.
submodule_update/fast:
	$(MAKE) -f CMakeFiles/submodule_update.dir/build.make CMakeFiles/submodule_update.dir/build
.PHONY : submodule_update/fast

#=============================================================================
# Target rules for targets named lwm2mclient

# Build rule for target.
lwm2mclient: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lwm2mclient
.PHONY : lwm2mclient

# fast build rule for target.
lwm2mclient/fast:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/build
.PHONY : lwm2mclient/fast

coap/block.o: coap/block.c.o

.PHONY : coap/block.o

# target to build an object file
coap/block.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/block.c.o
.PHONY : coap/block.c.o

coap/block.i: coap/block.c.i

.PHONY : coap/block.i

# target to preprocess a source file
coap/block.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/block.c.i
.PHONY : coap/block.c.i

coap/block.s: coap/block.c.s

.PHONY : coap/block.s

# target to generate assembly for a file
coap/block.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/block.c.s
.PHONY : coap/block.c.s

coap/er-coap-13/er-coap-13.o: coap/er-coap-13/er-coap-13.c.o

.PHONY : coap/er-coap-13/er-coap-13.o

# target to build an object file
coap/er-coap-13/er-coap-13.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/er-coap-13/er-coap-13.c.o
.PHONY : coap/er-coap-13/er-coap-13.c.o

coap/er-coap-13/er-coap-13.i: coap/er-coap-13/er-coap-13.c.i

.PHONY : coap/er-coap-13/er-coap-13.i

# target to preprocess a source file
coap/er-coap-13/er-coap-13.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/er-coap-13/er-coap-13.c.i
.PHONY : coap/er-coap-13/er-coap-13.c.i

coap/er-coap-13/er-coap-13.s: coap/er-coap-13/er-coap-13.c.s

.PHONY : coap/er-coap-13/er-coap-13.s

# target to generate assembly for a file
coap/er-coap-13/er-coap-13.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/er-coap-13/er-coap-13.c.s
.PHONY : coap/er-coap-13/er-coap-13.c.s

coap/transaction.o: coap/transaction.c.o

.PHONY : coap/transaction.o

# target to build an object file
coap/transaction.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/transaction.c.o
.PHONY : coap/transaction.c.o

coap/transaction.i: coap/transaction.c.i

.PHONY : coap/transaction.i

# target to preprocess a source file
coap/transaction.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/transaction.c.i
.PHONY : coap/transaction.c.i

coap/transaction.s: coap/transaction.c.s

.PHONY : coap/transaction.s

# target to generate assembly for a file
coap/transaction.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/coap/transaction.c.s
.PHONY : coap/transaction.c.s

core/bootstrap.o: core/bootstrap.c.o

.PHONY : core/bootstrap.o

# target to build an object file
core/bootstrap.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/bootstrap.c.o
.PHONY : core/bootstrap.c.o

core/bootstrap.i: core/bootstrap.c.i

.PHONY : core/bootstrap.i

# target to preprocess a source file
core/bootstrap.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/bootstrap.c.i
.PHONY : core/bootstrap.c.i

core/bootstrap.s: core/bootstrap.c.s

.PHONY : core/bootstrap.s

# target to generate assembly for a file
core/bootstrap.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/bootstrap.c.s
.PHONY : core/bootstrap.c.s

core/discover.o: core/discover.c.o

.PHONY : core/discover.o

# target to build an object file
core/discover.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/discover.c.o
.PHONY : core/discover.c.o

core/discover.i: core/discover.c.i

.PHONY : core/discover.i

# target to preprocess a source file
core/discover.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/discover.c.i
.PHONY : core/discover.c.i

core/discover.s: core/discover.c.s

.PHONY : core/discover.s

# target to generate assembly for a file
core/discover.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/discover.c.s
.PHONY : core/discover.c.s

core/liblwm2m.o: core/liblwm2m.c.o

.PHONY : core/liblwm2m.o

# target to build an object file
core/liblwm2m.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/liblwm2m.c.o
.PHONY : core/liblwm2m.c.o

core/liblwm2m.i: core/liblwm2m.c.i

.PHONY : core/liblwm2m.i

# target to preprocess a source file
core/liblwm2m.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/liblwm2m.c.i
.PHONY : core/liblwm2m.c.i

core/liblwm2m.s: core/liblwm2m.c.s

.PHONY : core/liblwm2m.s

# target to generate assembly for a file
core/liblwm2m.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/liblwm2m.c.s
.PHONY : core/liblwm2m.c.s

core/list.o: core/list.c.o

.PHONY : core/list.o

# target to build an object file
core/list.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/list.c.o
.PHONY : core/list.c.o

core/list.i: core/list.c.i

.PHONY : core/list.i

# target to preprocess a source file
core/list.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/list.c.i
.PHONY : core/list.c.i

core/list.s: core/list.c.s

.PHONY : core/list.s

# target to generate assembly for a file
core/list.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/list.c.s
.PHONY : core/list.c.s

core/management.o: core/management.c.o

.PHONY : core/management.o

# target to build an object file
core/management.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/management.c.o
.PHONY : core/management.c.o

core/management.i: core/management.c.i

.PHONY : core/management.i

# target to preprocess a source file
core/management.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/management.c.i
.PHONY : core/management.c.i

core/management.s: core/management.c.s

.PHONY : core/management.s

# target to generate assembly for a file
core/management.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/management.c.s
.PHONY : core/management.c.s

core/objects.o: core/objects.c.o

.PHONY : core/objects.o

# target to build an object file
core/objects.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/objects.c.o
.PHONY : core/objects.c.o

core/objects.i: core/objects.c.i

.PHONY : core/objects.i

# target to preprocess a source file
core/objects.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/objects.c.i
.PHONY : core/objects.c.i

core/objects.s: core/objects.c.s

.PHONY : core/objects.s

# target to generate assembly for a file
core/objects.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/objects.c.s
.PHONY : core/objects.c.s

core/observe.o: core/observe.c.o

.PHONY : core/observe.o

# target to build an object file
core/observe.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/observe.c.o
.PHONY : core/observe.c.o

core/observe.i: core/observe.c.i

.PHONY : core/observe.i

# target to preprocess a source file
core/observe.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/observe.c.i
.PHONY : core/observe.c.i

core/observe.s: core/observe.c.s

.PHONY : core/observe.s

# target to generate assembly for a file
core/observe.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/observe.c.s
.PHONY : core/observe.c.s

core/packet.o: core/packet.c.o

.PHONY : core/packet.o

# target to build an object file
core/packet.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/packet.c.o
.PHONY : core/packet.c.o

core/packet.i: core/packet.c.i

.PHONY : core/packet.i

# target to preprocess a source file
core/packet.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/packet.c.i
.PHONY : core/packet.c.i

core/packet.s: core/packet.c.s

.PHONY : core/packet.s

# target to generate assembly for a file
core/packet.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/packet.c.s
.PHONY : core/packet.c.s

core/registration.o: core/registration.c.o

.PHONY : core/registration.o

# target to build an object file
core/registration.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/registration.c.o
.PHONY : core/registration.c.o

core/registration.i: core/registration.c.i

.PHONY : core/registration.i

# target to preprocess a source file
core/registration.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/registration.c.i
.PHONY : core/registration.c.i

core/registration.s: core/registration.c.s

.PHONY : core/registration.s

# target to generate assembly for a file
core/registration.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/registration.c.s
.PHONY : core/registration.c.s

core/uri.o: core/uri.c.o

.PHONY : core/uri.o

# target to build an object file
core/uri.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/uri.c.o
.PHONY : core/uri.c.o

core/uri.i: core/uri.c.i

.PHONY : core/uri.i

# target to preprocess a source file
core/uri.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/uri.c.i
.PHONY : core/uri.c.i

core/uri.s: core/uri.c.s

.PHONY : core/uri.s

# target to generate assembly for a file
core/uri.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/uri.c.s
.PHONY : core/uri.c.s

core/utils.o: core/utils.c.o

.PHONY : core/utils.o

# target to build an object file
core/utils.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/utils.c.o
.PHONY : core/utils.c.o

core/utils.i: core/utils.c.i

.PHONY : core/utils.i

# target to preprocess a source file
core/utils.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/utils.c.i
.PHONY : core/utils.c.i

core/utils.s: core/utils.c.s

.PHONY : core/utils.s

# target to generate assembly for a file
core/utils.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/core/utils.c.s
.PHONY : core/utils.c.s

data/data.o: data/data.c.o

.PHONY : data/data.o

# target to build an object file
data/data.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/data.c.o
.PHONY : data/data.c.o

data/data.i: data/data.c.i

.PHONY : data/data.i

# target to preprocess a source file
data/data.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/data.c.i
.PHONY : data/data.c.i

data/data.s: data/data.c.s

.PHONY : data/data.s

# target to generate assembly for a file
data/data.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/data.c.s
.PHONY : data/data.c.s

data/json.o: data/json.c.o

.PHONY : data/json.o

# target to build an object file
data/json.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/json.c.o
.PHONY : data/json.c.o

data/json.i: data/json.c.i

.PHONY : data/json.i

# target to preprocess a source file
data/json.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/json.c.i
.PHONY : data/json.c.i

data/json.s: data/json.c.s

.PHONY : data/json.s

# target to generate assembly for a file
data/json.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/json.c.s
.PHONY : data/json.c.s

data/json_common.o: data/json_common.c.o

.PHONY : data/json_common.o

# target to build an object file
data/json_common.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/json_common.c.o
.PHONY : data/json_common.c.o

data/json_common.i: data/json_common.c.i

.PHONY : data/json_common.i

# target to preprocess a source file
data/json_common.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/json_common.c.i
.PHONY : data/json_common.c.i

data/json_common.s: data/json_common.c.s

.PHONY : data/json_common.s

# target to generate assembly for a file
data/json_common.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/json_common.c.s
.PHONY : data/json_common.c.s

data/senml_json.o: data/senml_json.c.o

.PHONY : data/senml_json.o

# target to build an object file
data/senml_json.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/senml_json.c.o
.PHONY : data/senml_json.c.o

data/senml_json.i: data/senml_json.c.i

.PHONY : data/senml_json.i

# target to preprocess a source file
data/senml_json.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/senml_json.c.i
.PHONY : data/senml_json.c.i

data/senml_json.s: data/senml_json.c.s

.PHONY : data/senml_json.s

# target to generate assembly for a file
data/senml_json.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/senml_json.c.s
.PHONY : data/senml_json.c.s

data/tlv.o: data/tlv.c.o

.PHONY : data/tlv.o

# target to build an object file
data/tlv.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/tlv.c.o
.PHONY : data/tlv.c.o

data/tlv.i: data/tlv.c.i

.PHONY : data/tlv.i

# target to preprocess a source file
data/tlv.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/tlv.c.i
.PHONY : data/tlv.c.i

data/tlv.s: data/tlv.c.s

.PHONY : data/tlv.s

# target to generate assembly for a file
data/tlv.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/data/tlv.c.s
.PHONY : data/tlv.c.s

examples/shared/commandline.o: examples/shared/commandline.c.o

.PHONY : examples/shared/commandline.o

# target to build an object file
examples/shared/commandline.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/commandline.c.o
.PHONY : examples/shared/commandline.c.o

examples/shared/commandline.i: examples/shared/commandline.c.i

.PHONY : examples/shared/commandline.i

# target to preprocess a source file
examples/shared/commandline.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/commandline.c.i
.PHONY : examples/shared/commandline.c.i

examples/shared/commandline.s: examples/shared/commandline.c.s

.PHONY : examples/shared/commandline.s

# target to generate assembly for a file
examples/shared/commandline.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/commandline.c.s
.PHONY : examples/shared/commandline.c.s

examples/shared/dtlsconnection.o: examples/shared/dtlsconnection.c.o

.PHONY : examples/shared/dtlsconnection.o

# target to build an object file
examples/shared/dtlsconnection.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/dtlsconnection.c.o
.PHONY : examples/shared/dtlsconnection.c.o

examples/shared/dtlsconnection.i: examples/shared/dtlsconnection.c.i

.PHONY : examples/shared/dtlsconnection.i

# target to preprocess a source file
examples/shared/dtlsconnection.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/dtlsconnection.c.i
.PHONY : examples/shared/dtlsconnection.c.i

examples/shared/dtlsconnection.s: examples/shared/dtlsconnection.c.s

.PHONY : examples/shared/dtlsconnection.s

# target to generate assembly for a file
examples/shared/dtlsconnection.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/dtlsconnection.c.s
.PHONY : examples/shared/dtlsconnection.c.s

examples/shared/memtrace.o: examples/shared/memtrace.c.o

.PHONY : examples/shared/memtrace.o

# target to build an object file
examples/shared/memtrace.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/memtrace.c.o
.PHONY : examples/shared/memtrace.c.o

examples/shared/memtrace.i: examples/shared/memtrace.c.i

.PHONY : examples/shared/memtrace.i

# target to preprocess a source file
examples/shared/memtrace.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/memtrace.c.i
.PHONY : examples/shared/memtrace.c.i

examples/shared/memtrace.s: examples/shared/memtrace.c.s

.PHONY : examples/shared/memtrace.s

# target to generate assembly for a file
examples/shared/memtrace.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/memtrace.c.s
.PHONY : examples/shared/memtrace.c.s

examples/shared/platform.o: examples/shared/platform.c.o

.PHONY : examples/shared/platform.o

# target to build an object file
examples/shared/platform.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/platform.c.o
.PHONY : examples/shared/platform.c.o

examples/shared/platform.i: examples/shared/platform.c.i

.PHONY : examples/shared/platform.i

# target to preprocess a source file
examples/shared/platform.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/platform.c.i
.PHONY : examples/shared/platform.c.i

examples/shared/platform.s: examples/shared/platform.c.s

.PHONY : examples/shared/platform.s

# target to generate assembly for a file
examples/shared/platform.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/platform.c.s
.PHONY : examples/shared/platform.c.s

examples/shared/tinydtls/aes/rijndael.o: examples/shared/tinydtls/aes/rijndael.c.o

.PHONY : examples/shared/tinydtls/aes/rijndael.o

# target to build an object file
examples/shared/tinydtls/aes/rijndael.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/aes/rijndael.c.o
.PHONY : examples/shared/tinydtls/aes/rijndael.c.o

examples/shared/tinydtls/aes/rijndael.i: examples/shared/tinydtls/aes/rijndael.c.i

.PHONY : examples/shared/tinydtls/aes/rijndael.i

# target to preprocess a source file
examples/shared/tinydtls/aes/rijndael.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/aes/rijndael.c.i
.PHONY : examples/shared/tinydtls/aes/rijndael.c.i

examples/shared/tinydtls/aes/rijndael.s: examples/shared/tinydtls/aes/rijndael.c.s

.PHONY : examples/shared/tinydtls/aes/rijndael.s

# target to generate assembly for a file
examples/shared/tinydtls/aes/rijndael.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/aes/rijndael.c.s
.PHONY : examples/shared/tinydtls/aes/rijndael.c.s

examples/shared/tinydtls/ccm.o: examples/shared/tinydtls/ccm.c.o

.PHONY : examples/shared/tinydtls/ccm.o

# target to build an object file
examples/shared/tinydtls/ccm.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/ccm.c.o
.PHONY : examples/shared/tinydtls/ccm.c.o

examples/shared/tinydtls/ccm.i: examples/shared/tinydtls/ccm.c.i

.PHONY : examples/shared/tinydtls/ccm.i

# target to preprocess a source file
examples/shared/tinydtls/ccm.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/ccm.c.i
.PHONY : examples/shared/tinydtls/ccm.c.i

examples/shared/tinydtls/ccm.s: examples/shared/tinydtls/ccm.c.s

.PHONY : examples/shared/tinydtls/ccm.s

# target to generate assembly for a file
examples/shared/tinydtls/ccm.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/ccm.c.s
.PHONY : examples/shared/tinydtls/ccm.c.s

examples/shared/tinydtls/crypto.o: examples/shared/tinydtls/crypto.c.o

.PHONY : examples/shared/tinydtls/crypto.o

# target to build an object file
examples/shared/tinydtls/crypto.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/crypto.c.o
.PHONY : examples/shared/tinydtls/crypto.c.o

examples/shared/tinydtls/crypto.i: examples/shared/tinydtls/crypto.c.i

.PHONY : examples/shared/tinydtls/crypto.i

# target to preprocess a source file
examples/shared/tinydtls/crypto.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/crypto.c.i
.PHONY : examples/shared/tinydtls/crypto.c.i

examples/shared/tinydtls/crypto.s: examples/shared/tinydtls/crypto.c.s

.PHONY : examples/shared/tinydtls/crypto.s

# target to generate assembly for a file
examples/shared/tinydtls/crypto.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/crypto.c.s
.PHONY : examples/shared/tinydtls/crypto.c.s

examples/shared/tinydtls/dtls.o: examples/shared/tinydtls/dtls.c.o

.PHONY : examples/shared/tinydtls/dtls.o

# target to build an object file
examples/shared/tinydtls/dtls.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls.c.o
.PHONY : examples/shared/tinydtls/dtls.c.o

examples/shared/tinydtls/dtls.i: examples/shared/tinydtls/dtls.c.i

.PHONY : examples/shared/tinydtls/dtls.i

# target to preprocess a source file
examples/shared/tinydtls/dtls.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls.c.i
.PHONY : examples/shared/tinydtls/dtls.c.i

examples/shared/tinydtls/dtls.s: examples/shared/tinydtls/dtls.c.s

.PHONY : examples/shared/tinydtls/dtls.s

# target to generate assembly for a file
examples/shared/tinydtls/dtls.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls.c.s
.PHONY : examples/shared/tinydtls/dtls.c.s

examples/shared/tinydtls/dtls_debug.o: examples/shared/tinydtls/dtls_debug.c.o

.PHONY : examples/shared/tinydtls/dtls_debug.o

# target to build an object file
examples/shared/tinydtls/dtls_debug.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls_debug.c.o
.PHONY : examples/shared/tinydtls/dtls_debug.c.o

examples/shared/tinydtls/dtls_debug.i: examples/shared/tinydtls/dtls_debug.c.i

.PHONY : examples/shared/tinydtls/dtls_debug.i

# target to preprocess a source file
examples/shared/tinydtls/dtls_debug.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls_debug.c.i
.PHONY : examples/shared/tinydtls/dtls_debug.c.i

examples/shared/tinydtls/dtls_debug.s: examples/shared/tinydtls/dtls_debug.c.s

.PHONY : examples/shared/tinydtls/dtls_debug.s

# target to generate assembly for a file
examples/shared/tinydtls/dtls_debug.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls_debug.c.s
.PHONY : examples/shared/tinydtls/dtls_debug.c.s

examples/shared/tinydtls/dtls_time.o: examples/shared/tinydtls/dtls_time.c.o

.PHONY : examples/shared/tinydtls/dtls_time.o

# target to build an object file
examples/shared/tinydtls/dtls_time.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls_time.c.o
.PHONY : examples/shared/tinydtls/dtls_time.c.o

examples/shared/tinydtls/dtls_time.i: examples/shared/tinydtls/dtls_time.c.i

.PHONY : examples/shared/tinydtls/dtls_time.i

# target to preprocess a source file
examples/shared/tinydtls/dtls_time.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls_time.c.i
.PHONY : examples/shared/tinydtls/dtls_time.c.i

examples/shared/tinydtls/dtls_time.s: examples/shared/tinydtls/dtls_time.c.s

.PHONY : examples/shared/tinydtls/dtls_time.s

# target to generate assembly for a file
examples/shared/tinydtls/dtls_time.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/dtls_time.c.s
.PHONY : examples/shared/tinydtls/dtls_time.c.s

examples/shared/tinydtls/ecc/ecc.o: examples/shared/tinydtls/ecc/ecc.c.o

.PHONY : examples/shared/tinydtls/ecc/ecc.o

# target to build an object file
examples/shared/tinydtls/ecc/ecc.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/ecc/ecc.c.o
.PHONY : examples/shared/tinydtls/ecc/ecc.c.o

examples/shared/tinydtls/ecc/ecc.i: examples/shared/tinydtls/ecc/ecc.c.i

.PHONY : examples/shared/tinydtls/ecc/ecc.i

# target to preprocess a source file
examples/shared/tinydtls/ecc/ecc.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/ecc/ecc.c.i
.PHONY : examples/shared/tinydtls/ecc/ecc.c.i

examples/shared/tinydtls/ecc/ecc.s: examples/shared/tinydtls/ecc/ecc.c.s

.PHONY : examples/shared/tinydtls/ecc/ecc.s

# target to generate assembly for a file
examples/shared/tinydtls/ecc/ecc.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/ecc/ecc.c.s
.PHONY : examples/shared/tinydtls/ecc/ecc.c.s

examples/shared/tinydtls/hmac.o: examples/shared/tinydtls/hmac.c.o

.PHONY : examples/shared/tinydtls/hmac.o

# target to build an object file
examples/shared/tinydtls/hmac.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/hmac.c.o
.PHONY : examples/shared/tinydtls/hmac.c.o

examples/shared/tinydtls/hmac.i: examples/shared/tinydtls/hmac.c.i

.PHONY : examples/shared/tinydtls/hmac.i

# target to preprocess a source file
examples/shared/tinydtls/hmac.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/hmac.c.i
.PHONY : examples/shared/tinydtls/hmac.c.i

examples/shared/tinydtls/hmac.s: examples/shared/tinydtls/hmac.c.s

.PHONY : examples/shared/tinydtls/hmac.s

# target to generate assembly for a file
examples/shared/tinydtls/hmac.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/hmac.c.s
.PHONY : examples/shared/tinydtls/hmac.c.s

examples/shared/tinydtls/netq.o: examples/shared/tinydtls/netq.c.o

.PHONY : examples/shared/tinydtls/netq.o

# target to build an object file
examples/shared/tinydtls/netq.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/netq.c.o
.PHONY : examples/shared/tinydtls/netq.c.o

examples/shared/tinydtls/netq.i: examples/shared/tinydtls/netq.c.i

.PHONY : examples/shared/tinydtls/netq.i

# target to preprocess a source file
examples/shared/tinydtls/netq.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/netq.c.i
.PHONY : examples/shared/tinydtls/netq.c.i

examples/shared/tinydtls/netq.s: examples/shared/tinydtls/netq.c.s

.PHONY : examples/shared/tinydtls/netq.s

# target to generate assembly for a file
examples/shared/tinydtls/netq.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/netq.c.s
.PHONY : examples/shared/tinydtls/netq.c.s

examples/shared/tinydtls/peer.o: examples/shared/tinydtls/peer.c.o

.PHONY : examples/shared/tinydtls/peer.o

# target to build an object file
examples/shared/tinydtls/peer.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/peer.c.o
.PHONY : examples/shared/tinydtls/peer.c.o

examples/shared/tinydtls/peer.i: examples/shared/tinydtls/peer.c.i

.PHONY : examples/shared/tinydtls/peer.i

# target to preprocess a source file
examples/shared/tinydtls/peer.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/peer.c.i
.PHONY : examples/shared/tinydtls/peer.c.i

examples/shared/tinydtls/peer.s: examples/shared/tinydtls/peer.c.s

.PHONY : examples/shared/tinydtls/peer.s

# target to generate assembly for a file
examples/shared/tinydtls/peer.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/peer.c.s
.PHONY : examples/shared/tinydtls/peer.c.s

examples/shared/tinydtls/session.o: examples/shared/tinydtls/session.c.o

.PHONY : examples/shared/tinydtls/session.o

# target to build an object file
examples/shared/tinydtls/session.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/session.c.o
.PHONY : examples/shared/tinydtls/session.c.o

examples/shared/tinydtls/session.i: examples/shared/tinydtls/session.c.i

.PHONY : examples/shared/tinydtls/session.i

# target to preprocess a source file
examples/shared/tinydtls/session.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/session.c.i
.PHONY : examples/shared/tinydtls/session.c.i

examples/shared/tinydtls/session.s: examples/shared/tinydtls/session.c.s

.PHONY : examples/shared/tinydtls/session.s

# target to generate assembly for a file
examples/shared/tinydtls/session.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/session.c.s
.PHONY : examples/shared/tinydtls/session.c.s

examples/shared/tinydtls/sha2/sha2.o: examples/shared/tinydtls/sha2/sha2.c.o

.PHONY : examples/shared/tinydtls/sha2/sha2.o

# target to build an object file
examples/shared/tinydtls/sha2/sha2.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/sha2/sha2.c.o
.PHONY : examples/shared/tinydtls/sha2/sha2.c.o

examples/shared/tinydtls/sha2/sha2.i: examples/shared/tinydtls/sha2/sha2.c.i

.PHONY : examples/shared/tinydtls/sha2/sha2.i

# target to preprocess a source file
examples/shared/tinydtls/sha2/sha2.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/sha2/sha2.c.i
.PHONY : examples/shared/tinydtls/sha2/sha2.c.i

examples/shared/tinydtls/sha2/sha2.s: examples/shared/tinydtls/sha2/sha2.c.s

.PHONY : examples/shared/tinydtls/sha2/sha2.s

# target to generate assembly for a file
examples/shared/tinydtls/sha2/sha2.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/examples/shared/tinydtls/sha2/sha2.c.s
.PHONY : examples/shared/tinydtls/sha2/sha2.c.s

lwm2mclient.o: lwm2mclient.c.o

.PHONY : lwm2mclient.o

# target to build an object file
lwm2mclient.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/lwm2mclient.c.o
.PHONY : lwm2mclient.c.o

lwm2mclient.i: lwm2mclient.c.i

.PHONY : lwm2mclient.i

# target to preprocess a source file
lwm2mclient.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/lwm2mclient.c.i
.PHONY : lwm2mclient.c.i

lwm2mclient.s: lwm2mclient.c.s

.PHONY : lwm2mclient.s

# target to generate assembly for a file
lwm2mclient.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/lwm2mclient.c.s
.PHONY : lwm2mclient.c.s

object_access_control.o: object_access_control.c.o

.PHONY : object_access_control.o

# target to build an object file
object_access_control.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_access_control.c.o
.PHONY : object_access_control.c.o

object_access_control.i: object_access_control.c.i

.PHONY : object_access_control.i

# target to preprocess a source file
object_access_control.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_access_control.c.i
.PHONY : object_access_control.c.i

object_access_control.s: object_access_control.c.s

.PHONY : object_access_control.s

# target to generate assembly for a file
object_access_control.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_access_control.c.s
.PHONY : object_access_control.c.s

object_connectivity_moni.o: object_connectivity_moni.c.o

.PHONY : object_connectivity_moni.o

# target to build an object file
object_connectivity_moni.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_connectivity_moni.c.o
.PHONY : object_connectivity_moni.c.o

object_connectivity_moni.i: object_connectivity_moni.c.i

.PHONY : object_connectivity_moni.i

# target to preprocess a source file
object_connectivity_moni.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_connectivity_moni.c.i
.PHONY : object_connectivity_moni.c.i

object_connectivity_moni.s: object_connectivity_moni.c.s

.PHONY : object_connectivity_moni.s

# target to generate assembly for a file
object_connectivity_moni.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_connectivity_moni.c.s
.PHONY : object_connectivity_moni.c.s

object_connectivity_stat.o: object_connectivity_stat.c.o

.PHONY : object_connectivity_stat.o

# target to build an object file
object_connectivity_stat.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_connectivity_stat.c.o
.PHONY : object_connectivity_stat.c.o

object_connectivity_stat.i: object_connectivity_stat.c.i

.PHONY : object_connectivity_stat.i

# target to preprocess a source file
object_connectivity_stat.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_connectivity_stat.c.i
.PHONY : object_connectivity_stat.c.i

object_connectivity_stat.s: object_connectivity_stat.c.s

.PHONY : object_connectivity_stat.s

# target to generate assembly for a file
object_connectivity_stat.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_connectivity_stat.c.s
.PHONY : object_connectivity_stat.c.s

object_device.o: object_device.c.o

.PHONY : object_device.o

# target to build an object file
object_device.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_device.c.o
.PHONY : object_device.c.o

object_device.i: object_device.c.i

.PHONY : object_device.i

# target to preprocess a source file
object_device.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_device.c.i
.PHONY : object_device.c.i

object_device.s: object_device.c.s

.PHONY : object_device.s

# target to generate assembly for a file
object_device.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_device.c.s
.PHONY : object_device.c.s

object_firmware.o: object_firmware.c.o

.PHONY : object_firmware.o

# target to build an object file
object_firmware.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_firmware.c.o
.PHONY : object_firmware.c.o

object_firmware.i: object_firmware.c.i

.PHONY : object_firmware.i

# target to preprocess a source file
object_firmware.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_firmware.c.i
.PHONY : object_firmware.c.i

object_firmware.s: object_firmware.c.s

.PHONY : object_firmware.s

# target to generate assembly for a file
object_firmware.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_firmware.c.s
.PHONY : object_firmware.c.s

object_location.o: object_location.c.o

.PHONY : object_location.o

# target to build an object file
object_location.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_location.c.o
.PHONY : object_location.c.o

object_location.i: object_location.c.i

.PHONY : object_location.i

# target to preprocess a source file
object_location.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_location.c.i
.PHONY : object_location.c.i

object_location.s: object_location.c.s

.PHONY : object_location.s

# target to generate assembly for a file
object_location.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_location.c.s
.PHONY : object_location.c.s

object_mysql_1.o: object_mysql_1.c.o

.PHONY : object_mysql_1.o

# target to build an object file
object_mysql_1.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_1.c.o
.PHONY : object_mysql_1.c.o

object_mysql_1.i: object_mysql_1.c.i

.PHONY : object_mysql_1.i

# target to preprocess a source file
object_mysql_1.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_1.c.i
.PHONY : object_mysql_1.c.i

object_mysql_1.s: object_mysql_1.c.s

.PHONY : object_mysql_1.s

# target to generate assembly for a file
object_mysql_1.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_1.c.s
.PHONY : object_mysql_1.c.s

object_mysql_10.o: object_mysql_10.c.o

.PHONY : object_mysql_10.o

# target to build an object file
object_mysql_10.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_10.c.o
.PHONY : object_mysql_10.c.o

object_mysql_10.i: object_mysql_10.c.i

.PHONY : object_mysql_10.i

# target to preprocess a source file
object_mysql_10.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_10.c.i
.PHONY : object_mysql_10.c.i

object_mysql_10.s: object_mysql_10.c.s

.PHONY : object_mysql_10.s

# target to generate assembly for a file
object_mysql_10.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_10.c.s
.PHONY : object_mysql_10.c.s

object_mysql_11.o: object_mysql_11.c.o

.PHONY : object_mysql_11.o

# target to build an object file
object_mysql_11.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_11.c.o
.PHONY : object_mysql_11.c.o

object_mysql_11.i: object_mysql_11.c.i

.PHONY : object_mysql_11.i

# target to preprocess a source file
object_mysql_11.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_11.c.i
.PHONY : object_mysql_11.c.i

object_mysql_11.s: object_mysql_11.c.s

.PHONY : object_mysql_11.s

# target to generate assembly for a file
object_mysql_11.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_11.c.s
.PHONY : object_mysql_11.c.s

object_mysql_12.o: object_mysql_12.c.o

.PHONY : object_mysql_12.o

# target to build an object file
object_mysql_12.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_12.c.o
.PHONY : object_mysql_12.c.o

object_mysql_12.i: object_mysql_12.c.i

.PHONY : object_mysql_12.i

# target to preprocess a source file
object_mysql_12.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_12.c.i
.PHONY : object_mysql_12.c.i

object_mysql_12.s: object_mysql_12.c.s

.PHONY : object_mysql_12.s

# target to generate assembly for a file
object_mysql_12.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_12.c.s
.PHONY : object_mysql_12.c.s

object_mysql_13.o: object_mysql_13.c.o

.PHONY : object_mysql_13.o

# target to build an object file
object_mysql_13.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_13.c.o
.PHONY : object_mysql_13.c.o

object_mysql_13.i: object_mysql_13.c.i

.PHONY : object_mysql_13.i

# target to preprocess a source file
object_mysql_13.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_13.c.i
.PHONY : object_mysql_13.c.i

object_mysql_13.s: object_mysql_13.c.s

.PHONY : object_mysql_13.s

# target to generate assembly for a file
object_mysql_13.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_13.c.s
.PHONY : object_mysql_13.c.s

object_mysql_14.o: object_mysql_14.c.o

.PHONY : object_mysql_14.o

# target to build an object file
object_mysql_14.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_14.c.o
.PHONY : object_mysql_14.c.o

object_mysql_14.i: object_mysql_14.c.i

.PHONY : object_mysql_14.i

# target to preprocess a source file
object_mysql_14.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_14.c.i
.PHONY : object_mysql_14.c.i

object_mysql_14.s: object_mysql_14.c.s

.PHONY : object_mysql_14.s

# target to generate assembly for a file
object_mysql_14.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_14.c.s
.PHONY : object_mysql_14.c.s

object_mysql_15.o: object_mysql_15.c.o

.PHONY : object_mysql_15.o

# target to build an object file
object_mysql_15.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_15.c.o
.PHONY : object_mysql_15.c.o

object_mysql_15.i: object_mysql_15.c.i

.PHONY : object_mysql_15.i

# target to preprocess a source file
object_mysql_15.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_15.c.i
.PHONY : object_mysql_15.c.i

object_mysql_15.s: object_mysql_15.c.s

.PHONY : object_mysql_15.s

# target to generate assembly for a file
object_mysql_15.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_15.c.s
.PHONY : object_mysql_15.c.s

object_mysql_16.o: object_mysql_16.c.o

.PHONY : object_mysql_16.o

# target to build an object file
object_mysql_16.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_16.c.o
.PHONY : object_mysql_16.c.o

object_mysql_16.i: object_mysql_16.c.i

.PHONY : object_mysql_16.i

# target to preprocess a source file
object_mysql_16.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_16.c.i
.PHONY : object_mysql_16.c.i

object_mysql_16.s: object_mysql_16.c.s

.PHONY : object_mysql_16.s

# target to generate assembly for a file
object_mysql_16.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_16.c.s
.PHONY : object_mysql_16.c.s

object_mysql_17.o: object_mysql_17.c.o

.PHONY : object_mysql_17.o

# target to build an object file
object_mysql_17.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_17.c.o
.PHONY : object_mysql_17.c.o

object_mysql_17.i: object_mysql_17.c.i

.PHONY : object_mysql_17.i

# target to preprocess a source file
object_mysql_17.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_17.c.i
.PHONY : object_mysql_17.c.i

object_mysql_17.s: object_mysql_17.c.s

.PHONY : object_mysql_17.s

# target to generate assembly for a file
object_mysql_17.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_17.c.s
.PHONY : object_mysql_17.c.s

object_mysql_18.o: object_mysql_18.c.o

.PHONY : object_mysql_18.o

# target to build an object file
object_mysql_18.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_18.c.o
.PHONY : object_mysql_18.c.o

object_mysql_18.i: object_mysql_18.c.i

.PHONY : object_mysql_18.i

# target to preprocess a source file
object_mysql_18.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_18.c.i
.PHONY : object_mysql_18.c.i

object_mysql_18.s: object_mysql_18.c.s

.PHONY : object_mysql_18.s

# target to generate assembly for a file
object_mysql_18.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_18.c.s
.PHONY : object_mysql_18.c.s

object_mysql_19.o: object_mysql_19.c.o

.PHONY : object_mysql_19.o

# target to build an object file
object_mysql_19.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_19.c.o
.PHONY : object_mysql_19.c.o

object_mysql_19.i: object_mysql_19.c.i

.PHONY : object_mysql_19.i

# target to preprocess a source file
object_mysql_19.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_19.c.i
.PHONY : object_mysql_19.c.i

object_mysql_19.s: object_mysql_19.c.s

.PHONY : object_mysql_19.s

# target to generate assembly for a file
object_mysql_19.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_19.c.s
.PHONY : object_mysql_19.c.s

object_mysql_2.o: object_mysql_2.c.o

.PHONY : object_mysql_2.o

# target to build an object file
object_mysql_2.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_2.c.o
.PHONY : object_mysql_2.c.o

object_mysql_2.i: object_mysql_2.c.i

.PHONY : object_mysql_2.i

# target to preprocess a source file
object_mysql_2.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_2.c.i
.PHONY : object_mysql_2.c.i

object_mysql_2.s: object_mysql_2.c.s

.PHONY : object_mysql_2.s

# target to generate assembly for a file
object_mysql_2.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_2.c.s
.PHONY : object_mysql_2.c.s

object_mysql_20.o: object_mysql_20.c.o

.PHONY : object_mysql_20.o

# target to build an object file
object_mysql_20.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_20.c.o
.PHONY : object_mysql_20.c.o

object_mysql_20.i: object_mysql_20.c.i

.PHONY : object_mysql_20.i

# target to preprocess a source file
object_mysql_20.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_20.c.i
.PHONY : object_mysql_20.c.i

object_mysql_20.s: object_mysql_20.c.s

.PHONY : object_mysql_20.s

# target to generate assembly for a file
object_mysql_20.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_20.c.s
.PHONY : object_mysql_20.c.s

object_mysql_21.o: object_mysql_21.c.o

.PHONY : object_mysql_21.o

# target to build an object file
object_mysql_21.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_21.c.o
.PHONY : object_mysql_21.c.o

object_mysql_21.i: object_mysql_21.c.i

.PHONY : object_mysql_21.i

# target to preprocess a source file
object_mysql_21.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_21.c.i
.PHONY : object_mysql_21.c.i

object_mysql_21.s: object_mysql_21.c.s

.PHONY : object_mysql_21.s

# target to generate assembly for a file
object_mysql_21.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_21.c.s
.PHONY : object_mysql_21.c.s

object_mysql_3.o: object_mysql_3.c.o

.PHONY : object_mysql_3.o

# target to build an object file
object_mysql_3.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_3.c.o
.PHONY : object_mysql_3.c.o

object_mysql_3.i: object_mysql_3.c.i

.PHONY : object_mysql_3.i

# target to preprocess a source file
object_mysql_3.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_3.c.i
.PHONY : object_mysql_3.c.i

object_mysql_3.s: object_mysql_3.c.s

.PHONY : object_mysql_3.s

# target to generate assembly for a file
object_mysql_3.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_3.c.s
.PHONY : object_mysql_3.c.s

object_mysql_4.o: object_mysql_4.c.o

.PHONY : object_mysql_4.o

# target to build an object file
object_mysql_4.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_4.c.o
.PHONY : object_mysql_4.c.o

object_mysql_4.i: object_mysql_4.c.i

.PHONY : object_mysql_4.i

# target to preprocess a source file
object_mysql_4.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_4.c.i
.PHONY : object_mysql_4.c.i

object_mysql_4.s: object_mysql_4.c.s

.PHONY : object_mysql_4.s

# target to generate assembly for a file
object_mysql_4.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_4.c.s
.PHONY : object_mysql_4.c.s

object_mysql_5.o: object_mysql_5.c.o

.PHONY : object_mysql_5.o

# target to build an object file
object_mysql_5.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_5.c.o
.PHONY : object_mysql_5.c.o

object_mysql_5.i: object_mysql_5.c.i

.PHONY : object_mysql_5.i

# target to preprocess a source file
object_mysql_5.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_5.c.i
.PHONY : object_mysql_5.c.i

object_mysql_5.s: object_mysql_5.c.s

.PHONY : object_mysql_5.s

# target to generate assembly for a file
object_mysql_5.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_5.c.s
.PHONY : object_mysql_5.c.s

object_mysql_6.o: object_mysql_6.c.o

.PHONY : object_mysql_6.o

# target to build an object file
object_mysql_6.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_6.c.o
.PHONY : object_mysql_6.c.o

object_mysql_6.i: object_mysql_6.c.i

.PHONY : object_mysql_6.i

# target to preprocess a source file
object_mysql_6.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_6.c.i
.PHONY : object_mysql_6.c.i

object_mysql_6.s: object_mysql_6.c.s

.PHONY : object_mysql_6.s

# target to generate assembly for a file
object_mysql_6.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_6.c.s
.PHONY : object_mysql_6.c.s

object_mysql_7.o: object_mysql_7.c.o

.PHONY : object_mysql_7.o

# target to build an object file
object_mysql_7.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_7.c.o
.PHONY : object_mysql_7.c.o

object_mysql_7.i: object_mysql_7.c.i

.PHONY : object_mysql_7.i

# target to preprocess a source file
object_mysql_7.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_7.c.i
.PHONY : object_mysql_7.c.i

object_mysql_7.s: object_mysql_7.c.s

.PHONY : object_mysql_7.s

# target to generate assembly for a file
object_mysql_7.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_7.c.s
.PHONY : object_mysql_7.c.s

object_mysql_8.o: object_mysql_8.c.o

.PHONY : object_mysql_8.o

# target to build an object file
object_mysql_8.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_8.c.o
.PHONY : object_mysql_8.c.o

object_mysql_8.i: object_mysql_8.c.i

.PHONY : object_mysql_8.i

# target to preprocess a source file
object_mysql_8.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_8.c.i
.PHONY : object_mysql_8.c.i

object_mysql_8.s: object_mysql_8.c.s

.PHONY : object_mysql_8.s

# target to generate assembly for a file
object_mysql_8.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_8.c.s
.PHONY : object_mysql_8.c.s

object_mysql_9.o: object_mysql_9.c.o

.PHONY : object_mysql_9.o

# target to build an object file
object_mysql_9.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_9.c.o
.PHONY : object_mysql_9.c.o

object_mysql_9.i: object_mysql_9.c.i

.PHONY : object_mysql_9.i

# target to preprocess a source file
object_mysql_9.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_9.c.i
.PHONY : object_mysql_9.c.i

object_mysql_9.s: object_mysql_9.c.s

.PHONY : object_mysql_9.s

# target to generate assembly for a file
object_mysql_9.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_mysql_9.c.s
.PHONY : object_mysql_9.c.s

object_security.o: object_security.c.o

.PHONY : object_security.o

# target to build an object file
object_security.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_security.c.o
.PHONY : object_security.c.o

object_security.i: object_security.c.i

.PHONY : object_security.i

# target to preprocess a source file
object_security.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_security.c.i
.PHONY : object_security.c.i

object_security.s: object_security.c.s

.PHONY : object_security.s

# target to generate assembly for a file
object_security.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_security.c.s
.PHONY : object_security.c.s

object_server.o: object_server.c.o

.PHONY : object_server.o

# target to build an object file
object_server.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_server.c.o
.PHONY : object_server.c.o

object_server.i: object_server.c.i

.PHONY : object_server.i

# target to preprocess a source file
object_server.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_server.c.i
.PHONY : object_server.c.i

object_server.s: object_server.c.s

.PHONY : object_server.s

# target to generate assembly for a file
object_server.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_server.c.s
.PHONY : object_server.c.s

object_test.o: object_test.c.o

.PHONY : object_test.o

# target to build an object file
object_test.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_test.c.o
.PHONY : object_test.c.o

object_test.i: object_test.c.i

.PHONY : object_test.i

# target to preprocess a source file
object_test.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_test.c.i
.PHONY : object_test.c.i

object_test.s: object_test.c.s

.PHONY : object_test.s

# target to generate assembly for a file
object_test.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/object_test.c.s
.PHONY : object_test.c.s

sensor_driver.o: sensor_driver.c.o

.PHONY : sensor_driver.o

# target to build an object file
sensor_driver.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/sensor_driver.c.o
.PHONY : sensor_driver.c.o

sensor_driver.i: sensor_driver.c.i

.PHONY : sensor_driver.i

# target to preprocess a source file
sensor_driver.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/sensor_driver.c.i
.PHONY : sensor_driver.c.i

sensor_driver.s: sensor_driver.c.s

.PHONY : sensor_driver.s

# target to generate assembly for a file
sensor_driver.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/sensor_driver.c.s
.PHONY : sensor_driver.c.s

system_api.o: system_api.c.o

.PHONY : system_api.o

# target to build an object file
system_api.c.o:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/system_api.c.o
.PHONY : system_api.c.o

system_api.i: system_api.c.i

.PHONY : system_api.i

# target to preprocess a source file
system_api.c.i:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/system_api.c.i
.PHONY : system_api.c.i

system_api.s: system_api.c.s

.PHONY : system_api.s

# target to generate assembly for a file
system_api.c.s:
	$(MAKE) -f CMakeFiles/lwm2mclient.dir/build.make CMakeFiles/lwm2mclient.dir/system_api.c.s
.PHONY : system_api.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... submodule_update"
	@echo "... lwm2mclient"
	@echo "... coap/block.o"
	@echo "... coap/block.i"
	@echo "... coap/block.s"
	@echo "... coap/er-coap-13/er-coap-13.o"
	@echo "... coap/er-coap-13/er-coap-13.i"
	@echo "... coap/er-coap-13/er-coap-13.s"
	@echo "... coap/transaction.o"
	@echo "... coap/transaction.i"
	@echo "... coap/transaction.s"
	@echo "... core/bootstrap.o"
	@echo "... core/bootstrap.i"
	@echo "... core/bootstrap.s"
	@echo "... core/discover.o"
	@echo "... core/discover.i"
	@echo "... core/discover.s"
	@echo "... core/liblwm2m.o"
	@echo "... core/liblwm2m.i"
	@echo "... core/liblwm2m.s"
	@echo "... core/list.o"
	@echo "... core/list.i"
	@echo "... core/list.s"
	@echo "... core/management.o"
	@echo "... core/management.i"
	@echo "... core/management.s"
	@echo "... core/objects.o"
	@echo "... core/objects.i"
	@echo "... core/objects.s"
	@echo "... core/observe.o"
	@echo "... core/observe.i"
	@echo "... core/observe.s"
	@echo "... core/packet.o"
	@echo "... core/packet.i"
	@echo "... core/packet.s"
	@echo "... core/registration.o"
	@echo "... core/registration.i"
	@echo "... core/registration.s"
	@echo "... core/uri.o"
	@echo "... core/uri.i"
	@echo "... core/uri.s"
	@echo "... core/utils.o"
	@echo "... core/utils.i"
	@echo "... core/utils.s"
	@echo "... data/data.o"
	@echo "... data/data.i"
	@echo "... data/data.s"
	@echo "... data/json.o"
	@echo "... data/json.i"
	@echo "... data/json.s"
	@echo "... data/json_common.o"
	@echo "... data/json_common.i"
	@echo "... data/json_common.s"
	@echo "... data/senml_json.o"
	@echo "... data/senml_json.i"
	@echo "... data/senml_json.s"
	@echo "... data/tlv.o"
	@echo "... data/tlv.i"
	@echo "... data/tlv.s"
	@echo "... examples/shared/commandline.o"
	@echo "... examples/shared/commandline.i"
	@echo "... examples/shared/commandline.s"
	@echo "... examples/shared/dtlsconnection.o"
	@echo "... examples/shared/dtlsconnection.i"
	@echo "... examples/shared/dtlsconnection.s"
	@echo "... examples/shared/memtrace.o"
	@echo "... examples/shared/memtrace.i"
	@echo "... examples/shared/memtrace.s"
	@echo "... examples/shared/platform.o"
	@echo "... examples/shared/platform.i"
	@echo "... examples/shared/platform.s"
	@echo "... examples/shared/tinydtls/aes/rijndael.o"
	@echo "... examples/shared/tinydtls/aes/rijndael.i"
	@echo "... examples/shared/tinydtls/aes/rijndael.s"
	@echo "... examples/shared/tinydtls/ccm.o"
	@echo "... examples/shared/tinydtls/ccm.i"
	@echo "... examples/shared/tinydtls/ccm.s"
	@echo "... examples/shared/tinydtls/crypto.o"
	@echo "... examples/shared/tinydtls/crypto.i"
	@echo "... examples/shared/tinydtls/crypto.s"
	@echo "... examples/shared/tinydtls/dtls.o"
	@echo "... examples/shared/tinydtls/dtls.i"
	@echo "... examples/shared/tinydtls/dtls.s"
	@echo "... examples/shared/tinydtls/dtls_debug.o"
	@echo "... examples/shared/tinydtls/dtls_debug.i"
	@echo "... examples/shared/tinydtls/dtls_debug.s"
	@echo "... examples/shared/tinydtls/dtls_time.o"
	@echo "... examples/shared/tinydtls/dtls_time.i"
	@echo "... examples/shared/tinydtls/dtls_time.s"
	@echo "... examples/shared/tinydtls/ecc/ecc.o"
	@echo "... examples/shared/tinydtls/ecc/ecc.i"
	@echo "... examples/shared/tinydtls/ecc/ecc.s"
	@echo "... examples/shared/tinydtls/hmac.o"
	@echo "... examples/shared/tinydtls/hmac.i"
	@echo "... examples/shared/tinydtls/hmac.s"
	@echo "... examples/shared/tinydtls/netq.o"
	@echo "... examples/shared/tinydtls/netq.i"
	@echo "... examples/shared/tinydtls/netq.s"
	@echo "... examples/shared/tinydtls/peer.o"
	@echo "... examples/shared/tinydtls/peer.i"
	@echo "... examples/shared/tinydtls/peer.s"
	@echo "... examples/shared/tinydtls/session.o"
	@echo "... examples/shared/tinydtls/session.i"
	@echo "... examples/shared/tinydtls/session.s"
	@echo "... examples/shared/tinydtls/sha2/sha2.o"
	@echo "... examples/shared/tinydtls/sha2/sha2.i"
	@echo "... examples/shared/tinydtls/sha2/sha2.s"
	@echo "... lwm2mclient.o"
	@echo "... lwm2mclient.i"
	@echo "... lwm2mclient.s"
	@echo "... object_access_control.o"
	@echo "... object_access_control.i"
	@echo "... object_access_control.s"
	@echo "... object_connectivity_moni.o"
	@echo "... object_connectivity_moni.i"
	@echo "... object_connectivity_moni.s"
	@echo "... object_connectivity_stat.o"
	@echo "... object_connectivity_stat.i"
	@echo "... object_connectivity_stat.s"
	@echo "... object_device.o"
	@echo "... object_device.i"
	@echo "... object_device.s"
	@echo "... object_firmware.o"
	@echo "... object_firmware.i"
	@echo "... object_firmware.s"
	@echo "... object_location.o"
	@echo "... object_location.i"
	@echo "... object_location.s"
	@echo "... object_mysql_1.o"
	@echo "... object_mysql_1.i"
	@echo "... object_mysql_1.s"
	@echo "... object_mysql_10.o"
	@echo "... object_mysql_10.i"
	@echo "... object_mysql_10.s"
	@echo "... object_mysql_11.o"
	@echo "... object_mysql_11.i"
	@echo "... object_mysql_11.s"
	@echo "... object_mysql_12.o"
	@echo "... object_mysql_12.i"
	@echo "... object_mysql_12.s"
	@echo "... object_mysql_13.o"
	@echo "... object_mysql_13.i"
	@echo "... object_mysql_13.s"
	@echo "... object_mysql_14.o"
	@echo "... object_mysql_14.i"
	@echo "... object_mysql_14.s"
	@echo "... object_mysql_15.o"
	@echo "... object_mysql_15.i"
	@echo "... object_mysql_15.s"
	@echo "... object_mysql_16.o"
	@echo "... object_mysql_16.i"
	@echo "... object_mysql_16.s"
	@echo "... object_mysql_17.o"
	@echo "... object_mysql_17.i"
	@echo "... object_mysql_17.s"
	@echo "... object_mysql_18.o"
	@echo "... object_mysql_18.i"
	@echo "... object_mysql_18.s"
	@echo "... object_mysql_19.o"
	@echo "... object_mysql_19.i"
	@echo "... object_mysql_19.s"
	@echo "... object_mysql_2.o"
	@echo "... object_mysql_2.i"
	@echo "... object_mysql_2.s"
	@echo "... object_mysql_20.o"
	@echo "... object_mysql_20.i"
	@echo "... object_mysql_20.s"
	@echo "... object_mysql_21.o"
	@echo "... object_mysql_21.i"
	@echo "... object_mysql_21.s"
	@echo "... object_mysql_3.o"
	@echo "... object_mysql_3.i"
	@echo "... object_mysql_3.s"
	@echo "... object_mysql_4.o"
	@echo "... object_mysql_4.i"
	@echo "... object_mysql_4.s"
	@echo "... object_mysql_5.o"
	@echo "... object_mysql_5.i"
	@echo "... object_mysql_5.s"
	@echo "... object_mysql_6.o"
	@echo "... object_mysql_6.i"
	@echo "... object_mysql_6.s"
	@echo "... object_mysql_7.o"
	@echo "... object_mysql_7.i"
	@echo "... object_mysql_7.s"
	@echo "... object_mysql_8.o"
	@echo "... object_mysql_8.i"
	@echo "... object_mysql_8.s"
	@echo "... object_mysql_9.o"
	@echo "... object_mysql_9.i"
	@echo "... object_mysql_9.s"
	@echo "... object_security.o"
	@echo "... object_security.i"
	@echo "... object_security.s"
	@echo "... object_server.o"
	@echo "... object_server.i"
	@echo "... object_server.s"
	@echo "... object_test.o"
	@echo "... object_test.i"
	@echo "... object_test.s"
	@echo "... sensor_driver.o"
	@echo "... sensor_driver.i"
	@echo "... sensor_driver.s"
	@echo "... system_api.o"
	@echo "... system_api.i"
	@echo "... system_api.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

