
/* addons.h generated by the gen_objects tool using my_objects as input */


/*
 * object_mysql_1.c
 */

#define MYSQL_1_ACTIVE          1
#define MYSQL_1_OBJECT          3303

lwm2m_object_t  *GLtestobject_1;
lwm2m_object_t * mysql_1_get(void);
void mysql_1_free(lwm2m_object_t * object);
void mysql_1_display(lwm2m_object_t * objectP);
uint8_t mysql_1_update(int, int, char *);

/*
 * object_mysql_2.c
 */

#define MYSQL_2_ACTIVE          1
#define MYSQL_2_OBJECT          3304

lwm2m_object_t  *GLtestobject_2;
lwm2m_object_t * mysql_2_get(void);
void mysql_2_free(lwm2m_object_t * object);
void mysql_2_display(lwm2m_object_t * objectP);
uint8_t mysql_2_update(int, int, char *);

/*
 * object_mysql_3.c
 */

#define MYSQL_3_ACTIVE          1
#define MYSQL_3_OBJECT          10266

lwm2m_object_t  *GLtestobject_3;
lwm2m_object_t * mysql_3_get(void);
void mysql_3_free(lwm2m_object_t * object);
void mysql_3_display(lwm2m_object_t * objectP);
uint8_t mysql_3_update(int, int, char *);

/*
 * object_mysql_4.c
 */

#define MYSQL_4_ACTIVE          1
#define MYSQL_4_OBJECT          10267

lwm2m_object_t  *GLtestobject_4;
lwm2m_object_t * mysql_4_get(void);
void mysql_4_free(lwm2m_object_t * object);
void mysql_4_display(lwm2m_object_t * objectP);
uint8_t mysql_4_update(int, int, char *);

/*
 * object_mysql_5.c
 */

#define MYSQL_5_ACTIVE          1
#define MYSQL_5_OBJECT          10268

lwm2m_object_t  *GLtestobject_5;
lwm2m_object_t * mysql_5_get(void);
void mysql_5_free(lwm2m_object_t * object);
void mysql_5_display(lwm2m_object_t * objectP);
uint8_t mysql_5_update(int, int, char *);

/*
 * object_mysql_6.c
 */

#define MYSQL_6_ACTIVE          1
#define MYSQL_6_OBJECT          10269

lwm2m_object_t  *GLtestobject_6;
lwm2m_object_t * mysql_6_get(void);
void mysql_6_free(lwm2m_object_t * object);
void mysql_6_display(lwm2m_object_t * objectP);
uint8_t mysql_6_update(int, int, char *);

/*
 * object_mysql_7.c
 */

#define MYSQL_7_ACTIVE          1
#define MYSQL_7_OBJECT          10270

lwm2m_object_t  *GLtestobject_7;
lwm2m_object_t * mysql_7_get(void);
void mysql_7_free(lwm2m_object_t * object);
void mysql_7_display(lwm2m_object_t * objectP);
uint8_t mysql_7_update(int, int, char *);

/*
 * object_mysql_8.c
 */

#define MYSQL_8_ACTIVE          1
#define MYSQL_8_OBJECT          10271

lwm2m_object_t  *GLtestobject_8;
lwm2m_object_t * mysql_8_get(void);
void mysql_8_free(lwm2m_object_t * object);
void mysql_8_display(lwm2m_object_t * objectP);
uint8_t mysql_8_update(int, int, char *);

/*
 * object_mysql_9.c
 */

#define MYSQL_9_ACTIVE          1
#define MYSQL_9_OBJECT          10272

lwm2m_object_t  *GLtestobject_9;
lwm2m_object_t * mysql_9_get(void);
void mysql_9_free(lwm2m_object_t * object);
void mysql_9_display(lwm2m_object_t * objectP);
uint8_t mysql_9_update(int, int, char *);

/*
 * object_mysql_10.c
 */

#define MYSQL_10_ACTIVE          1
#define MYSQL_10_OBJECT          10273

lwm2m_object_t  *GLtestobject_10;
lwm2m_object_t * mysql_10_get(void);
void mysql_10_free(lwm2m_object_t * object);
void mysql_10_display(lwm2m_object_t * objectP);
uint8_t mysql_10_update(int, int, char *);

/*
 * object_mysql_11.c
 */

#define MYSQL_11_ACTIVE          1
#define MYSQL_11_OBJECT          10274

lwm2m_object_t  *GLtestobject_11;
lwm2m_object_t * mysql_11_get(void);
void mysql_11_free(lwm2m_object_t * object);
void mysql_11_display(lwm2m_object_t * objectP);
uint8_t mysql_11_update(int, int, char *);

/*
 * object_mysql_12.c
 */

#define MYSQL_12_ACTIVE          1
#define MYSQL_12_OBJECT          10275

lwm2m_object_t  *GLtestobject_12;
lwm2m_object_t * mysql_12_get(void);
void mysql_12_free(lwm2m_object_t * object);
void mysql_12_display(lwm2m_object_t * objectP);
uint8_t mysql_12_update(int, int, char *);

/*
 * object_mysql_13.c
 */

#define MYSQL_13_ACTIVE          1
#define MYSQL_13_OBJECT          10276

lwm2m_object_t  *GLtestobject_13;
lwm2m_object_t * mysql_13_get(void);
void mysql_13_free(lwm2m_object_t * object);
void mysql_13_display(lwm2m_object_t * objectP);
uint8_t mysql_13_update(int, int, char *);

/*
 * object_mysql_14.c
 */

#define MYSQL_14_ACTIVE          1
#define MYSQL_14_OBJECT          10277

lwm2m_object_t  *GLtestobject_14;
lwm2m_object_t * mysql_14_get(void);
void mysql_14_free(lwm2m_object_t * object);
void mysql_14_display(lwm2m_object_t * objectP);
uint8_t mysql_14_update(int, int, char *);

/*
 * object_mysql_15.c
 */

#define MYSQL_15_ACTIVE          1
#define MYSQL_15_OBJECT          10278

lwm2m_object_t  *GLtestobject_15;
lwm2m_object_t * mysql_15_get(void);
void mysql_15_free(lwm2m_object_t * object);
void mysql_15_display(lwm2m_object_t * objectP);
uint8_t mysql_15_update(int, int, char *);

/*
 * object_mysql_16.c
 */

#define MYSQL_16_ACTIVE          1
#define MYSQL_16_OBJECT          10279

lwm2m_object_t  *GLtestobject_16;
lwm2m_object_t * mysql_16_get(void);
void mysql_16_free(lwm2m_object_t * object);
void mysql_16_display(lwm2m_object_t * objectP);
uint8_t mysql_16_update(int, int, char *);

/*
 * object_mysql_17.c
 */

#define MYSQL_17_ACTIVE          1
#define MYSQL_17_OBJECT          10280

lwm2m_object_t  *GLtestobject_17;
lwm2m_object_t * mysql_17_get(void);
void mysql_17_free(lwm2m_object_t * object);
void mysql_17_display(lwm2m_object_t * objectP);
uint8_t mysql_17_update(int, int, char *);

/*
 * object_mysql_18.c
 */

#define MYSQL_18_ACTIVE          1
#define MYSQL_18_OBJECT          10281

lwm2m_object_t  *GLtestobject_18;
lwm2m_object_t * mysql_18_get(void);
void mysql_18_free(lwm2m_object_t * object);
void mysql_18_display(lwm2m_object_t * objectP);
uint8_t mysql_18_update(int, int, char *);

/*
 * object_mysql_19.c
 */

#define MYSQL_19_ACTIVE          1
#define MYSQL_19_OBJECT          10282

lwm2m_object_t  *GLtestobject_19;
lwm2m_object_t * mysql_19_get(void);
void mysql_19_free(lwm2m_object_t * object);
void mysql_19_display(lwm2m_object_t * objectP);
uint8_t mysql_19_update(int, int, char *);

/*
 * object_mysql_20.c
 */

#define MYSQL_20_ACTIVE          1
#define MYSQL_20_OBJECT          10283

lwm2m_object_t  *GLtestobject_20;
lwm2m_object_t * mysql_20_get(void);
void mysql_20_free(lwm2m_object_t * object);
void mysql_20_display(lwm2m_object_t * objectP);
uint8_t mysql_20_update(int, int, char *);

/*
 * object_mysql_21.c
 */

#define MYSQL_21_ACTIVE          1
#define MYSQL_21_OBJECT          10284

lwm2m_object_t  *GLtestobject_21;
lwm2m_object_t * mysql_21_get(void);
void mysql_21_free(lwm2m_object_t * object);
void mysql_21_display(lwm2m_object_t * objectP);
uint8_t mysql_21_update(int, int, char *);

